import { sidebar } from 'vuepress-theme-hope';

export const javaSidebarConfig = {
    '/java/': [
        {
            text: 'Java 基础',
            prefix: 'java-base/',
            collapsible: true,
            children: [
                {
                    text: 'Api使用',
                    prefix: 'api/',
                    collapsible: true,
                    children: ['1-base', '2-thread', '3-bigDecimal', '4-map', '6-stream', '7-jackson'],
                },
                {
                    text: '并发编程',
                    prefix: 'concurrent/',
                    collapsible: true,
                    children: [
                        '1-base',
                        '2-cas',
                        '4-juc-lock',
                        '5-synchronized',
                        '1-concurrent',
                        '5-juc-con',
                        '3-method',
                        '4-signalCommunication',
                        '7-threadpool',
                    ],
                },
            ],
        },
        {
            text: 'JVM',
            prefix: 'java-jvm/',
            collapsible: true,
            children: [
                '1-jvm',
                '2-jvm',
                '3-rundata',
                '4-object',
                '5-jvm',
                '6-classfile',
                '7-gc',
                '8-classload',
                '9-optimize',
            ],
        },
        {
            text: 'IO',
            prefix: 'java-io/',
            collapsible: true,
            children: [
                '1-tcp',
                '1-nio',
                '2-netty-base',
                '3-netty-advanc',
            ],
        },
        "version",
        "mockito",
        {
            text: 'Mybatis',
            prefix: 'java-mybatis/',
            collapsible: true,
            children: [
                'JDBC',
                '1-custom-persistence',
                '2-architecture',
                '3-advanced-application',
                '4-plugin',
                '5-cache',
                'MybatisPlus',
            ],
        },
        {
            text: 'Spring',
            prefix: 'spring/',
            collapsible: true,
            children: [
                '1-base',
                '2-ioc',
                '3-springbean',
                '4-event',
                '5-environment',
                '6-model',
                '7-util',
                '8-servlet',
                '10-beanPost',
            ],
        },
    {
            text: 'SpringCloud',
            prefix: 'springcloud/',
            collapsible: true,
            children: [
                '0-base',
                '1-register-Center',
                '2-load-balance',
                '3-restful',
                '4-gateway',
                '4-distributed-transaction',
                '5-trafficFault-tolerant',
                '6-full-link-log',
            ],
        },
    ],
};